/* autogenerated by Processing revision 1277 on 2021-12-16 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class hellomouse extends PApplet {

 public void setup() {
  /* size commented out by preprocessor */;
  stroke(255);
}

 public void draw() {
  line(150, 25, mouseX, mouseY);
}

 public void mousePressed() {
  background(192, 64, 0);
}


  public void settings() { size(400, 400); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "hellomouse" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
